import type { ConfigCountExportColumn, ConfigItemValidationDynamicsGP, ConfigItemValidationFaster } from './types.js';
declare const _default: {
    'modules.inventoryScanner.isEnabled': boolean;
    'modules.inventoryScanner.apiIpAddressRegex': RegExp;
    'modules.inventoryScanner.scannerIpAddressRegex': RegExp;
    'modules.inventoryScanner.fasterSync.integrationId': number | undefined;
    'modules.inventoryScanner.fasterSync.exportFileNamePrefix': string;
    'modules.inventoryScanner.fasterSync.ftpPath': string;
    'modules.inventoryScanner.fasterSync.defaultTechnicianId': number;
    'modules.inventoryScanner.fasterSync.ntfy.isEnabled': boolean;
    'modules.inventoryScanner.fasterSync.ntfy.topic': string | undefined;
    'modules.inventoryScanner.workOrders.acceptNotValidated': boolean;
    'modules.inventoryScanner.workOrders.fasterRegex': RegExp;
    'modules.inventoryScanner.workOrders.acceptWorkTech': boolean;
    'modules.inventoryScanner.workOrders.workTechRegex': RegExp;
    'modules.inventoryScanner.workOrders.validationSources': Array<"fasterApi" | "worktech">;
    'modules.inventoryScanner.items.acceptNotValidated': boolean;
    'modules.inventoryScanner.items.itemNumberRegex': RegExp | undefined;
    'modules.inventoryScanner.items.placeholder': string;
    'modules.inventoryScanner.items.validation': ConfigItemValidationDynamicsGP | ConfigItemValidationFaster | undefined;
    'modules.inventoryScanner.fasterItemRequests.isEnabled': boolean;
    'modules.inventoryScanner.fasterItemRequests.ntfy.isEnabled': boolean;
    'modules.inventoryScanner.fasterItemRequests.ntfy.topic': string | undefined;
    'modules.inventoryScanner.quantities.acceptNegatives': boolean;
    'modules.inventoryScanner.quantities.acceptOverages': boolean;
    'modules.inventoryScanner.countExport.columns': ConfigCountExportColumn[];
};
export default _default;
