export default {
    'modules.inventoryScanner.isEnabled': false,
    'modules.inventoryScanner.scannerIpAddressRegex': /^$/,
    'modules.inventoryScanner.fasterSync.integrationId': undefined,
    'modules.inventoryScanner.fasterSync.exportFileNamePrefix': '',
    'modules.inventoryScanner.fasterSync.ftpPath': '',
    'modules.inventoryScanner.fasterSync.defaultTechnicianId': 1,
    'modules.inventoryScanner.fasterSync.ntfy.isEnabled': false,
    'modules.inventoryScanner.fasterSync.ntfy.topic': undefined,
    'modules.inventoryScanner.workOrders.acceptNotValidated': true,
    'modules.inventoryScanner.workOrders.fasterRegex': /^\d+$/,
    'modules.inventoryScanner.workOrders.acceptWorkTech': false,
    'modules.inventoryScanner.workOrders.workTechRegex': /^[A-Z]{2,3}.\d{2}.\d{5}$/,
    'modules.inventoryScanner.workOrders.validationSources': [],
    'modules.inventoryScanner.items.acceptNotValidated': true,
    'modules.inventoryScanner.items.itemNumberRegex': undefined,
    'modules.inventoryScanner.items.placeholder': '',
    'modules.inventoryScanner.items.validation': undefined,
    'modules.inventoryScanner.fasterItemRequests.isEnabled': false,
    'modules.inventoryScanner.fasterItemRequests.ntfy.isEnabled': false,
    'modules.inventoryScanner.fasterItemRequests.ntfy.topic': undefined,
    'modules.inventoryScanner.quantities.acceptNegatives': true,
    'modules.inventoryScanner.quantities.acceptOverages': true
};
