name: Coverage Testing

on: [workflow_dispatch, push, pull_request]

permissions: read-all

jobs:
  Coverage:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [18, 20, 21]
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}

    name: Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Install Application
        run: npm ci

      - name: Install Global Dependencies
        run: npm install -g c8 cross-env cypress@14

      - name: Copy Test Config
        run: cp ./data/config.testing.js ./data/config.js

      - name: Verify Cypress
        run: cypress verify
        env:
          CYPRESS_VERIFY_TIMEOUT: 600000

      - name: Run Coverage Testing
        run: npm run coverage

      - name: Codecov
        if: ${{ github.event_name != 'pull_request' && env.CODECOV_TOKEN != '' && matrix.node == 20 }}
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -t ${CODECOV_TOKEN}

      - name: DeepSource
        if: ${{ github.event_name != 'pull_request' && env.DEEPSOURCE_DSN != '' && matrix.node == 20 }}
        run: |
          # Install deepsource CLI
          curl https://deepsource.io/cli | sh
    
          # From the root directory, run the report coverage command
          ./bin/deepsource report --analyzer test-coverage --key javascript --value-file ./coverage/lcov.info
